### ISSUE TITLE
Question about ULIP and ULIP-2

### ISSUE THREAD

**Issue by gyjung975** [auniquesun/PPT#1]
Hi. Thanks for your great work!

I have a question about ULIP.
In the manuscript, ULIP (Point-BERT) is used, 
but in the code, ULIP-2 (Point-BERT) is used. (--ulip2)

My reproduction also shows similar results to the paper when using ULIP-2.

Are the results in the paper from ULIP-2?

**Comment by auniquesun** [comment]
@gyjung975 Since the codebase of original ULIP and ULIP-2 is same, the difference is that ULIP-2 is pre-trained on a much larger dataset. In our work, we load the pre-trained weights of ULIP-2.

**Comment by gyjung975** [comment]
Thank you for your timely reply!
